---
title: "CS201 Flexdashboard Assignment"
author: "Izack Takazawa"
date: 11/30/2024
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    source_code: embed
    theme:
      bootswatch: flatly
    navbar:
      - title: "Izack Takazawa"
        href: "https://izacktakazawa.github.io/"
        align: right
      - icon: "fa fa-github"
        href: "https://github.com/IzackTakazawa"
        align: right
        target: blank
    includes:
      after_body: ./docs/footer.html

---

```{r setup, include=FALSE}
library(flexdashboard)
library(here)
library(tidyverse)
library(janitor)
library(plotly)
library(dplyr)
```

```{r}
pitching <- read_csv(here("data/NYM_pitching.csv"))

pitching <- pitching %>%
  clean_names()
```

## Row {data-width="650"}

### Jacob deGrom and Max Scherzer's Best Years with the Mets Combined Graph

```{r}
degrom_stats <- pitching %>%
  filter(name == "Jacob deGrom")

scherzer_stats <- pitching %>%
  filter(name == "Max Scherzer")

# Combine both deGrom and Scherzers data and rename
combined_stats <- bind_rows(degrom_stats, scherzer_stats) %>%
  select(name, year, age, batters_faced, innings_pitched, hits_allowed, home_runs_allowed, earned_run_average, strikeouts, walks_allowed, strikeout_walk_ratio) %>%
  rename(
    Name = name,
    Year = year,
    Age = age,
    `Batters Faced` = batters_faced,
    `Innings Pitched` = innings_pitched,
    `Hits Allowed` = hits_allowed,
    `Home Runs Allowed` = home_runs_allowed,
    `Earned Run Average` = earned_run_average,
    Strikeouts = strikeouts,
    `Walks Allowed` = walks_allowed,
    `Strikeout Walk Ratio` = strikeout_walk_ratio
  )
# Find each pitcher's best year based on lowest ERA
best_year <- combined_stats %>%
  group_by(Name) %>%
  slice_min(order_by = `Earned Run Average`, n = 1) %>%
  ungroup()


best_year_plot_data <- best_year %>%
  pivot_longer(
    cols = -c(Name, Year, Age),
    names_to = "stat",
    values_to = "value"
  )

# Plot
best_year_plot <- ggplot(best_year_plot_data, aes(x = stat, y = value, fill = Name, text = paste(
    "Pitcher:", Name,
    "<br>Year:", Year,
    "<br>Age:", Age,
    "<br>Statistic:", stat,
    "<br>Value:", value
  ))) +
  geom_col(position = "dodge", show.legend = TRUE) +
  geom_text(aes(label = value),
            position = position_dodge(width = 0.9), 
            vjust = -0.5,
            size = 4,) +
  labs(
    title = "Comparison of Jacob deGrom and Max Scherzer",
    x = "Statistics",
    y = "Values",
    fill = "Pitcher"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
                               
    axis.text.y = element_text(size = 14),
    
    axis.title.x = element_text(size = 16, face = "bold"),
    
    axis.title.y = element_text(size = 16, face = "bold"),
    
    plot.title = element_text(size = 20, face = "bold"),  
    
    plot.subtitle = element_text(size = 16, face = "italic"),  
    
    legend.title = element_text(size = 14),  
    
    legend.text = element_text(size = 12),
    
    plot.caption = element_text(size = 8, hjust = 0.5, vjust = -1)
  ) +
  scale_fill_brewer(palette = "Set2")

#plotly
interactive_plot <- ggplotly(best_year_plot, tooltip = "text")

interactive_plot

```


------------------------------------------------------------------------

## Row {data-width="350"}

### Jacob deGrom's Career with the Mets

```{r}
jacob_degrom <- pitching %>%
  filter(name == "Jacob deGrom")

pitcher_stats <- jacob_degrom %>%
  select(name, year, age, batters_faced, innings_pitched, hits_allowed, home_runs_allowed, earned_run_average, strikeouts, walks_allowed, strikeout_walk_ratio) %>%
  rename(
    Name = name,
    Year = year,
    Age = age,
    `Batters Faced` = batters_faced,
    `Innings Pitched` = innings_pitched,
    `Hits Allowed` = hits_allowed,
    `Home Runs Allowed` = home_runs_allowed,
    `Earned Run Average` = earned_run_average,
    Strikeouts = strikeouts,
    `Walks Allowed` = walks_allowed,
    `Strikeout Walk Ratio` = strikeout_walk_ratio
  ) %>%
  pivot_longer(cols = c(`Batters Faced`, `Innings Pitched`, `Hits Allowed`, `Home Runs Allowed`, `Earned Run Average`, Strikeouts, `Walks Allowed`, `Strikeout Walk Ratio`), names_to = "stat", values_to = "value")

# Plot
degrom_interactive <- ggplot(pitcher_stats, aes(x = stat, y = value, fill = stat, text = paste(
    "<br>Age:", as.character(Age),  # Convert Age to character
    "<br>Statistic:", stat,
    "<br>Value:", value)))+
  geom_col(show.legend = FALSE, position = "dodge") +
  facet_wrap(~Year) +
  scale_fill_brewer(palette = "Set3") + 
  labs(
    title = "Jacob deGrom with the Mets",
    x = "Statistics",
    y = "Values"
  ) +
  theme_minimal(base_size = 14) + 
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size = 8),  
    axis.title.x = element_text(size = 10),  
    axis.title.y = element_text(size = 10), 
    strip.text = element_text(size = 10)
  )

# Plotly
interactive_degrom_plot <- ggplotly(degrom_interactive, tooltip = "text")

interactive_degrom_plot

```

### Max Scherzer's Career with the Mets

```{r}
max_scher <- pitching %>%
  filter(name == "Max Scherzer")

pitcher_stats <- max_scher %>%
  select(name, year, age, batters_faced, innings_pitched, hits_allowed, home_runs_allowed, earned_run_average, strikeouts, walks_allowed, strikeout_walk_ratio) %>%
  rename(
    Name = name,
    Year = year,
    Age = age,
    `Batters Faced` = batters_faced,
    `Innings Pitched` = innings_pitched,
    `Hits Allowed` = hits_allowed,
    `Home Runs Allowed` = home_runs_allowed,
    `Earned Run Average` = earned_run_average,
    Strikeouts = strikeouts,
    `Walks Allowed` = walks_allowed,
    `Strikeout Walk Ratio` = strikeout_walk_ratio
  ) %>%
  pivot_longer(cols = c(`Batters Faced`, `Innings Pitched`, `Hits Allowed`, `Home Runs Allowed`, `Earned Run Average`, Strikeouts, `Walks Allowed`, `Strikeout Walk Ratio`), names_to = "stat", values_to = "value")

# Plot
scher_interactive <- ggplot(pitcher_stats, aes(x = stat, y = value, fill = stat, text = paste(
    "<br>Age:", as.character(Age),  # Convert Age to character
    "<br>Statistic:", stat,
    "<br>Value:", value)))+
  geom_col(show.legend = FALSE, position = "dodge") +
  facet_wrap(~Year) + 
  scale_fill_brewer(palette = "Set3") + 
  labs(
    title = "Max Scherzer with the Mets",
    x = "Statistics",
    y = "Values"
  ) +
  theme_minimal(base_size = 14) + 
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_text(size = 8),  
    axis.title.x = element_text(size = 10),  
    axis.title.y = element_text(size = 10), 
    strip.text = element_text(size = 10)
  )

# Plotly
interactive_scher_plot <- ggplotly(scher_interactive, tooltip = "text")

interactive_scher_plot

```

---------

